# -*- coding: utf-8 -*-

from .acc_dataset import ds


# fmt: off
class AccountEnum:
    admin = ds.accounts["admin"]
    fat01 = ds.accounts["fat01"]
    fat02 = ds.accounts["fat02"]
    fat03 = ds.accounts["fat03"]
    fat04 = ds.accounts["fat04"]
    fat05 = ds.accounts["fat05"]
    fat06 = ds.accounts["fat06"]
    fat07 = ds.accounts["fat07"]
    fat08 = ds.accounts["fat08"]
    fat09 = ds.accounts["fat09"]
    fat10 = ds.accounts["fat10"]
    fat11 = ds.accounts["fat11"]
    fat12 = ds.accounts["fat12"]
    fat13 = ds.accounts["fat13"]
    fat14 = ds.accounts["fat14"]
    fat15 = ds.accounts["fat15"]
    fat16 = ds.accounts["fat16"]
    fat17 = ds.accounts["fat17"]
    fat18 = ds.accounts["fat18"]
    fat19 = ds.accounts["fat19"]
    fat20 = ds.accounts["fat20"]
    fat21 = ds.accounts["fat21"]
    fat22 = ds.accounts["fat22"]
    fat23 = ds.accounts["fat23"]
    fat24 = ds.accounts["fat24"]
    fat25 = ds.accounts["fat25"]


class RealmEnum:
    admin_AzerothCore = ds.accounts["admin"].realms_mapper["AzerothCore"]
    fat01_AzerothCore = ds.accounts["fat01"].realms_mapper["AzerothCore"]
    fat02_AzerothCore = ds.accounts["fat02"].realms_mapper["AzerothCore"]
    fat03_AzerothCore = ds.accounts["fat03"].realms_mapper["AzerothCore"]
    fat04_AzerothCore = ds.accounts["fat04"].realms_mapper["AzerothCore"]
    fat05_AzerothCore = ds.accounts["fat05"].realms_mapper["AzerothCore"]
    fat06_AzerothCore = ds.accounts["fat06"].realms_mapper["AzerothCore"]
    fat07_AzerothCore = ds.accounts["fat07"].realms_mapper["AzerothCore"]
    fat08_AzerothCore = ds.accounts["fat08"].realms_mapper["AzerothCore"]
    fat09_AzerothCore = ds.accounts["fat09"].realms_mapper["AzerothCore"]
    fat10_AzerothCore = ds.accounts["fat10"].realms_mapper["AzerothCore"]
    fat11_AzerothCore = ds.accounts["fat11"].realms_mapper["AzerothCore"]
    fat12_AzerothCore = ds.accounts["fat12"].realms_mapper["AzerothCore"]
    fat13_AzerothCore = ds.accounts["fat13"].realms_mapper["AzerothCore"]
    fat14_AzerothCore = ds.accounts["fat14"].realms_mapper["AzerothCore"]
    fat15_AzerothCore = ds.accounts["fat15"].realms_mapper["AzerothCore"]
    fat16_AzerothCore = ds.accounts["fat16"].realms_mapper["AzerothCore"]
    fat17_AzerothCore = ds.accounts["fat17"].realms_mapper["AzerothCore"]
    fat18_AzerothCore = ds.accounts["fat18"].realms_mapper["AzerothCore"]
    fat19_AzerothCore = ds.accounts["fat19"].realms_mapper["AzerothCore"]
    fat20_AzerothCore = ds.accounts["fat20"].realms_mapper["AzerothCore"]
    fat21_AzerothCore = ds.accounts["fat21"].realms_mapper["AzerothCore"]
    fat22_AzerothCore = ds.accounts["fat22"].realms_mapper["AzerothCore"]
    fat23_AzerothCore = ds.accounts["fat23"].realms_mapper["AzerothCore"]
    fat24_AzerothCore = ds.accounts["fat24"].realms_mapper["AzerothCore"]
    fat25_AzerothCore = ds.accounts["fat25"].realms_mapper["AzerothCore"]


class CharacterEnum:
    admin_AzerothCore_admin = ds.accounts["admin"].realms_mapper["AzerothCore"].characters_mapper["admin"]
    fat01_AzerothCore_ra = ds.accounts["fat01"].realms_mapper["AzerothCore"].characters_mapper["ra"]
    fat02_AzerothCore_rb = ds.accounts["fat02"].realms_mapper["AzerothCore"].characters_mapper["rb"]
    fat03_AzerothCore_rc = ds.accounts["fat03"].realms_mapper["AzerothCore"].characters_mapper["rc"]
    fat04_AzerothCore_rd = ds.accounts["fat04"].realms_mapper["AzerothCore"].characters_mapper["rd"]
    fat05_AzerothCore_re = ds.accounts["fat05"].realms_mapper["AzerothCore"].characters_mapper["re"]
    fat06_AzerothCore_rf = ds.accounts["fat06"].realms_mapper["AzerothCore"].characters_mapper["rf"]
    fat07_AzerothCore_rg = ds.accounts["fat07"].realms_mapper["AzerothCore"].characters_mapper["rg"]
    fat08_AzerothCore_rh = ds.accounts["fat08"].realms_mapper["AzerothCore"].characters_mapper["rh"]
    fat09_AzerothCore_ri = ds.accounts["fat09"].realms_mapper["AzerothCore"].characters_mapper["ri"]
    fat10_AzerothCore_rj = ds.accounts["fat10"].realms_mapper["AzerothCore"].characters_mapper["rj"]
    fat11_AzerothCore_rk = ds.accounts["fat11"].realms_mapper["AzerothCore"].characters_mapper["rk"]
    fat12_AzerothCore_rl = ds.accounts["fat12"].realms_mapper["AzerothCore"].characters_mapper["rl"]
    fat13_AzerothCore_rm = ds.accounts["fat13"].realms_mapper["AzerothCore"].characters_mapper["rm"]
    fat14_AzerothCore_rn = ds.accounts["fat14"].realms_mapper["AzerothCore"].characters_mapper["rn"]
    fat15_AzerothCore_ro = ds.accounts["fat15"].realms_mapper["AzerothCore"].characters_mapper["ro"]
    fat16_AzerothCore_rp = ds.accounts["fat16"].realms_mapper["AzerothCore"].characters_mapper["rp"]
    fat17_AzerothCore_rq = ds.accounts["fat17"].realms_mapper["AzerothCore"].characters_mapper["rq"]
    fat18_AzerothCore_rr = ds.accounts["fat18"].realms_mapper["AzerothCore"].characters_mapper["rr"]
    fat19_AzerothCore_rs = ds.accounts["fat19"].realms_mapper["AzerothCore"].characters_mapper["rs"]
    fat20_AzerothCore_rt = ds.accounts["fat20"].realms_mapper["AzerothCore"].characters_mapper["rt"]
    fat21_AzerothCore_ru = ds.accounts["fat21"].realms_mapper["AzerothCore"].characters_mapper["ru"]
    fat22_AzerothCore_rv = ds.accounts["fat22"].realms_mapper["AzerothCore"].characters_mapper["rv"]
    fat23_AzerothCore_rw = ds.accounts["fat23"].realms_mapper["AzerothCore"].characters_mapper["rw"]
    fat24_AzerothCore_rx = ds.accounts["fat24"].realms_mapper["AzerothCore"].characters_mapper["rx"]
    fat25_AzerothCore_ry = ds.accounts["fat25"].realms_mapper["AzerothCore"].characters_mapper["ry"]
# fmt: on